name: Test HAR library and CLI

on:
  pull_request:

  push:
    branches:
      - master
      - github-actions

jobs:
  main:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install LDC
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-latest

      - name: Build har
        run: dub build

      - name: Run library tests
        run: |
          set -eux
          dub run :test_library
          make check_clean_git

      - name: Run CLI tests
        run: |
          set -eux
          dub run :test_command_line_tool
          make check_clean_git

      - name: Validate Makefile
        run: |
          set -eux
          git clean -dfx
          make DC=ldmd2
          make check_clean_git
